### ISSUE TITLE
Make use of underscore for imports consistent.

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#101]
For example, we currently use a mix of:

```python
from ..parameters import Color as _Color
```

and

```python
from .parameters import Color
```

**Comment by laurensvalk** [comment]
Let's also check if typing imports need underscores, or if autocomplete is smart enough to exclude those even without underscores.

**Comment by dlech** [comment]
I'm pretty sure Pyright is smart enough now to exclude imports (it used to not be the case) so we should be able to drop the leading underscores everywhere. For cases where we do want an import to be visible (e.g. the `Motor` class), we need to explicitly export it, so those imports will still need to be imported as a different name, whether it is `_Motor` or `CommonMotor` doesn't really matter to me.

**Comment by laurensvalk** [comment]
Other things to make consistent: Use `...` instead of `pass` where applicable.

**Comment by laurensvalk** [comment]
In some cases it seems underscores do show up:

![image](https://user-images.githubusercontent.com/12326241/175762956-ad72168a-37ce-47e9-b103-bb7507e1b400.png)

Here it looks OK:

![image](https://user-images.githubusercontent.com/12326241/175762935-513924fd-3ea4-41a2-957a-f645ec435dc5.png)

**Comment by laurensvalk** [comment]
The ultrasonic sensor case above looks fixed.

Is there anything left to do here?

**Comment by dlech** [comment]
I don't think we made things completely consistent, but everything was reworked to be compatible with jedi code completion.
