### ISSUE TITLE
Set BETA flag correctly in npm release

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#102]
To build the docs with beta features enabled, we add `BETA=1` so we get, e.g.:

```python
make -C doc html TAG=IDE BETA=1
```

It would be nice to make this work with the npm build somehow.

**Comment by dlech** [comment]
Why do we need this flag? Shouldn't there just be one version of the docs at this point that matches the firmware?

**Comment by laurensvalk** [comment]
yep, that's probably a better idea
