### ISSUE TITLE
EV3Dev2 vs PyBricks2: Which is better?

### ISSUE THREAD

**Issue by Strolledlmp942** [pybricks/pybricks-api#111]
I'll be competing in WRO 2023, and I was planning to use Pybricks2, but one of my teammates suggested to use ev3dev2 instead. We asked our teacher for information about which one is better, which my teacher responded he hadn't any information. For more information about which is better I search on the internet and after some searching, I was not able to find any information. For me and my team this is a very important decision due that the program we choose is going to be use for the next 4 years by our team and then is going to be the one that is going to be teach to the next team.

**Comment by dlech** [comment]
This is a hard question to answer because what is best for me might not be best for you and your team. What are some important features of the software that would help you do better in the competition?

**Comment by laurensvalk** [comment]
See also https://github.com/pybricks/pybricks-api/issues/22.

**Comment by Strolledlmp942** [comment]
What me and my team mostly need it's the capability for it to use a PID, for the PID to be precise, not having too many variables, being reliable, for it to fast in performing and loading a program, and a small bonus it's for it to be capable of using a neuronal network (this one is not really needed due to my team and I not being sure about using it yet). The PID is the most important one due to it being our main way to adjust correctly and move around the track.

**Comment by laurensvalk** [comment]
As you'll see in https://github.com/pybricks/pybricks-api/issues/22, Pybricks might be closer to what you need in terms of drive accuracy and configurable PID settings.

**Comment by Strolledlmp942** [comment]
Alright thank you for your help and thank you for this information is going to be very useful in deciding which program to use.
