### ISSUE TITLE
Some pages blocked by robot.txt

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#138]
Just opening an issue to look into this later.

![image](https://user-images.githubusercontent.com/12326241/235420118-408282b9-32f0-4bb9-8170-0bd778399be9.png)

**Comment by dlech** [comment]
Since this is the v3.1.0 version, I think this is intentional on the part of readthedocs.org. They probably only allow crawling the default version of the docs so google doesn't end up with duplicate results for each version.
