### ISSUE TITLE
Regroup hubs on main page

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#34]
Currently, we have this on the main page:

![image](https://user-images.githubusercontent.com/12326241/97104306-2a536e80-16b3-11eb-9e15-fd6f63fb7a9b.png)

But MoveHub, CityHub, and TechnicHub all link to the same Powered Up quickstart page.

Instead, we need only three images/links:
- EV3 (Links to EV3 Quickstart)
- MoveHub / TechnicHub / CityHub (Links to Powered Up Quickstart)
- PrimeHub / InventorHub  (Links to SPIKE/MINDSTORMS Quickstart, which does not exist yet)

We'll still have pictures for individual hubs in #33 .

**Comment by dlech** [comment]
EV3 should probably also have a link to the v2.0 docs for users who want the stable version.

**Comment by laurensvalk** [comment]
> EV3 should probably also have a link to the v2.0 docs for users who want the stable version.

Good idea. Done via https://github.com/pybricks/pybricks-api/commit/b29dab4d6b9a4ac2f29b217388fd92908a8cf5b2

**Comment by laurensvalk** [comment]
Done in https://github.com/pybricks/pybricks-api/commit/bcf610a29ee750ebc74eb5dea8647de3fbd628e7

Looks like this now:

![image](https://user-images.githubusercontent.com/12326241/97118459-3a4a6d00-170a-11eb-905a-56d35dada456.png)
