### ISSUE TITLE
Special build for Pybricks Code

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#39]
Since EV3 doesn't work with Pybricks Code, it would be helpful if we could add some [ifconfig](https://www.sphinx-doc.org/en/master/usage/extensions/ifconfig.html) around the EV3 stuff so we can make a Powered Up-only version of the docs. The HTML output of this configuration should be packaged in a JavaScript package so that we can pull it in to Pybricks Code. This will allow Pybricks Code to be a fully offline app and will hopefully reduce confusion about EV3 not working with Pybricks Code.

**Comment by laurensvalk** [comment]
Since `pybricks-api` is set up for multiple targets already, another thing we could do is split off the EV3 docs altogether. But maybe we'll need to look at what to do with future EV3 support first.

**Comment by laurensvalk** [comment]
This is now available by building 

```
poetry run make -C doc SOURCEDIR=ide html
```

**Comment by laurensvalk** [comment]
> Since EV3 doesn't work with Pybricks Code, it would be helpful if we could add some ifconfig around the EV3 stuff so we can make a Powered Up-only version of the docs.

Done

> The HTML output of this configuration should be packaged in a JavaScript package so that we can pull it in to Pybricks Code. This will allow Pybricks Code to be a fully offline app and will hopefully reduce confusion about EV3 not working with Pybricks Code.

This is still to be done, assigning @dlech.
