### ISSUE TITLE
PDF broken

### ISSUE THREAD

**Issue by Alitai12** [pybricks/pybricks-api#40]
The PDF is broken from Site 72-173. Also Site 16.

https://docs.pybricks.com/_/downloads/en/latest/pdf/

Thanks for all your work.

**Comment by laurensvalk** [comment]
Thanks for reporting! We're restructuring the docs in #41 and #33 to be a bit more standard. Hopefully, this will also resolve this broken PDF layout as well.

Fixes are being pushed to the `work` branch, so let's keep an eye on this [pdf](https://docs.pybricks.com/_/downloads/en/work/pdf/) to see if things look better once the issues above are resolved.

**Comment by laurensvalk** [comment]
This is still broken, so the `contentui` plugin wasn't causing it. Let's wait for #20.

**Comment by laurensvalk** [comment]
This is finally fixed! :smile:
