### ISSUE TITLE
Menu layout is broken on RTD

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#55]
![image](https://user-images.githubusercontent.com/12326241/113918460-c0eb9600-97e2-11eb-8a72-273f01d37d27.png)

It's supposed to look like this:

![image](https://user-images.githubusercontent.com/12326241/113918517-d2cd3900-97e2-11eb-9857-9559eb1a27d3.png)

**Comment by laurensvalk** [comment]
It's weird that the work build, the very same commit, looks fine --- https://docs.pybricks.com/en/work/

Forcing a rebuild on RTD doesn't seem to help.

**Comment by laurensvalk** [comment]
Do you see this locally @dlech ?

**Comment by dlech** [comment]
No, it is working for me locally as well. The only difference that looks suspicious was the docutils version. The logs on readthedocs.org show it is using v0.17 but we have v0.16 in our lock file. sphinx-rtd-theme made a new release recently that excludes 0.17, so I made a PR to try it out to see if that works.

**Comment by laurensvalk** [comment]
This seems to be fixed, thanks!
