### ISSUE TITLE
Video is broken

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#58]
https://code.pybricks.com/static/docs/start_pup.html#installing-the-pybricks-firmware

![image](https://user-images.githubusercontent.com/963645/114438047-dbc85c80-9b8c-11eb-8b74-05c116cb106d.png)

**Comment by laurensvalk** [comment]
The installation guide isn't part of these docs.

This will get fixed once the latest Pybricks-code is published, which [has the new docs](https://github.com/pybricks/pybricks-code/pull/401).
