### ISSUE TITLE
Show typing in docs and drop separate return type

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#62]
Once #61 is complete, we can show typing in the docs.

Then we can also drop the separate return type, which will make functions like these a bit more compact:

![image](https://user-images.githubusercontent.com/12326241/124728023-87c0e000-df0f-11eb-8d48-1f03fc892d90.png)

**Comment by laurensvalk** [comment]
We can keep the "return type" to designate units instead, only where applicable, for the best of both approaches.

**Comment by dlech** [comment]
As mentioned in https://github.com/pybricks/pybricks-api/commit/a0ea0d8ca0ad3ff8e055a30ae77a682f06ca3dfd#commitcomment-53598577, type hints that are good for autocompletion engines are not always good for docs, so we may need to come up with a way to get a simplified function declaration to appear in the docs while keeping the complex type hints in the stubs `.py` files.

**Comment by laurensvalk** [comment]
> It's probably worth rethinking how we want all of this to show up. Some function signatures get much more complicated than necesary when showing type hints there.
> 
> There is a Sphinx option to show type hints in the argument description, in the signature, or both.

This seems like the right balance:

![image](https://user-images.githubusercontent.com/12326241/132179408-31e15bac-8a3d-499f-b4fd-eddab7d8e400.png)
![image](https://user-images.githubusercontent.com/12326241/132179454-bb81e8df-6573-40d9-803c-72ed9acef0cc.png)

Now we just need to make Sphinx actually do this.

**Comment by laurensvalk** [comment]
This is all done for Pybricks modules. We just need to continue for MicroPython modules, which is tracked in #63 .
