### ISSUE TITLE
Document included MicroPython modules

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#63]
The differences with upstream MicroPython, LEGO MicroPython, and CPython are too subtle, so we can't really get away with just linking to those. 

Instead, we should just explicity document all functions that come with the Pybricks firmware. We can still link to upstream sources for each method, but only when doing so provides useful additional information (rather than confuse things).

- [x] builtins
- [x] umath
- [x] uio
- [x] ustruct
- [x] micropython EDIT: Need to write args as bullet point consistent with rest.
- [x] usys
- [x] uselect
- [x] ujson
- [x] urandom 
- [x] uerrno 
- [x] Clean up Exceptions page with OSError section

**Comment by laurensvalk** [comment]
Also include a page for all builtins, like `round`, or `pow`.

**Comment by laurensvalk** [comment]
First draft of `umath` can be previewed [here](https://docs.pybricks.com/en/work/micropython/umath.html) for discussion.

**Comment by dlech** [comment]
I was actually working on this yesterday. I have all of the modules done, including builtins. Although I just copied from existing documentation and didn't fix it up that much.

**Comment by laurensvalk** [comment]
Builtins are done now.

**Comment by laurensvalk** [comment]
This is done :tada:.

A first pass, anyway. There are places to improve further, but this makes it presentable enough.
