### ISSUE TITLE
Style changes when upgrading to Sphinx 4.1

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#70]
A few things appear to have changed with v4.1. One noticable difference is that v3.X has method names in black, and arguments in gray. In v4 everything is just gray, which is slightly less readable.

### Old (left), new (right)
![image](https://user-images.githubusercontent.com/12326241/125617232-3acbbd3c-14eb-4149-a12b-97464c2af3c2.png)

**Comment by laurensvalk** [comment]
Similarly, functions are now all blue, with the old style being clearer:

![image](https://user-images.githubusercontent.com/12326241/125617646-6c678cb4-0019-49f5-bf20-9040e0e3fd66.png)

**Comment by dlech** [comment]
Upstream is working on it: https://github.com/readthedocs/sphinx_rtd_theme/pull/1123

**Comment by laurensvalk** [comment]
Meanwhile, the other blocking hacks have been removed, so we can upgrade once the aforementioned style issues are fixed.

**Comment by laurensvalk** [comment]
Upstream has committed a fix. Although not released yet, I might go ahead and pull this to considerably simplify work in #72.

![image](https://user-images.githubusercontent.com/12326241/128482111-bccf0c54-0fc3-4902-b964-d64085791d58.png)

One new minor change seems that `literals` may now break to a new line, but this is something we can look at another time.
