### ISSUE TITLE
Display docstrings correctly

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#72]
@dlech [wrote](https://github.com/pybricks/pybricks-api/commit/a0ea0d8ca0ad3ff8e055a30ae77a682f06ca3dfd).

> FYI, to make autocompletion work correctly, stubs need to consider autocompletion first and documentation second. We can always "fake" the documentation by not using autoclass in the .rst files if needed.

> For better autocompletion of standard library types, we should refer to typeshed. For example enumerate should be properly typed as https://github.com/python/typeshed/blob/6d6250f10963b8ad7aeeba387c8d48dc9d0cb92b/stdlib/builtins.pyi#L910.

**Comment by laurensvalk** [comment]
> We can always "fake" the documentation by not using autoclass in the .rst files if needed.

Sphinx did not pick up overloading correctly when using `autofunction` so we might have to do a bit of hacking to make this work.

**Comment by laurensvalk** [comment]
For special cases we could have one definition for Sphinx and another for typing, perhaps using `if/else` or a decorator to make it pick the right one.

**Comment by laurensvalk** [comment]
> For special cases we could have one definition for Sphinx and another for typing, perhaps using if/else or a decorator to make it pick the right one.

Sphinx seems to ignore such conditionals. For example, if you do:

```python

if True:
    class complex:

           # overload init 3 times

else:
    class complex:

           # overload init 2 times

```
My idea was to pick one on Sphinx and the other for typing, but Sphinx just overloads it 5 times.

The same goes for conditionals within the class definition.

**Comment by laurensvalk** [comment]
As these special cases probably mostly apply to `ubuiltins`, maybe we could just have a dedicated typing file for this one.

**Comment by dlech** [comment]
Can we not override the signatures by putting the desired signature for documentation as the first line of the doc string? [relevant docs](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_docstring_signature)

```python
class complex:
    @overload
    def __init__(self, ...):
        ...

    @overload
    def __init__(self, ...):
        ...

    @overload
    def __init__(self, ...):
        ...

    def __init__(self, ...):
        """
        __init__(self, ...) \ __init__(self, ...)

        ...
        """
```

It also looks like there are some hooks for modifying the signature: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#event-autodoc-before-process-signature.

**Comment by laurensvalk** [comment]
Thanks! I did not know we could do overloading with this as well. This looks like it should work nicely.

**Comment by laurensvalk** [comment]
> Can we not override the signatures by putting the desired signature for documentation as the first line of the doc string?

Apparently not in the version we are using, but it looks like it might work in 4.0, pending #70.

One caveat is that it appears to show ``None`` as a return type by default, which is a bit confusing for classes.

![image](https://user-images.githubusercontent.com/12326241/128478917-9dbd087f-44c1-4cd4-8849-0c737e29c158.png)

**Comment by laurensvalk** [comment]
Another thing I don't really like (even in the current version) is the lack of parenthesis for the signature without arguments. I know this the standard for classes in now, but it does not make sense in this overloaded context.

**Comment by laurensvalk** [comment]
It's also not going to solve things like `enumerate` being displayed as a class, but I think we can live with that for the upcoming release.

**Comment by laurensvalk** [comment]
The generics and guidelines are now resolved. We can make specific issues to fix the typing implementation of specific functions and classes.
