### ISSUE TITLE
Publish latest releases to PyPI

### ISSUE THREAD

**Issue by fkleon** [pybricks/pybricks-api#73]
Hi

The published packages on PyPI are outdated. As of today the latest published stable release on pypi is `2.0.0.post1` and the latest pre-release `3.0.0rc1`.

As far as I can tell the latest stable release should be `3.0.0` and the latest pre-release `3.1.0a3` as per [pybricks-micropython](https://github.com/pybricks/pybricks-micropython/releases) release page.

While it's easy to install this from git, there are no corresponding tags on the pybricks-api repository so it's a bit of a guesswork to get the right commit.

**Comment by dlech** [comment]
`3.1.0rc1` has just been published.
