### ISSUE TITLE
wrong parameter name in type hint file

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#76]
Just some minor stuff: the auto-complete signature for `DriveBase.drive(...)` -- e.g., on VSCode -- continues to show the `drive_speed=...` argument, instead of just `speed=...`.

Please see the attached screenshot.

Thank you.

Vinh

<img width="760" alt="Screen Shot 2021-07-30 at 13 04 43" src="https://user-images.githubusercontent.com/7796578/127706416-9fb7d033-520f-4e84-a32b-770eadbfdcfc.png">

_Originally posted by @TheVinhLuong102 in https://github.com/pybricks/pybricks-api/issues/23#issuecomment-890126963_

**Comment by TheVinhLuong102** [comment]
Thanks for the quick fix, David!
