### ISSUE TITLE
`uerrno` is not listed in table of contents

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#78]
Combining exceptions and error codes makes sense since they are closely related. But from the point of view of discoverability (e.g. a user, familiar with Python but not Pybricks, sees `import uerrno` and wants to known what this is) it is not possible to find `uerrno` in the docs without resorting to the search function unless you already know that it contains error codes. And from the point of view of consistency, all other modules get their own page, so why not `uerrno`?

**Comment by laurensvalk** [comment]
For discoverability, we could get it to show up in the table of contents by just changing the header line to `====` and change the title so it looks consistent:

![image](https://user-images.githubusercontent.com/12326241/127711461-e5e742f5-8bc8-4abc-974c-ed1042894af1.png)

Once we do that, I don't think a separate page would be worth it just for consistency. `uerrrno` is of little use without `OSErrors`, and it makes sense to keep examples about exceptions together so it's easier to see which one to use.

**Comment by dlech** [comment]
> just changing the header line to `====`

If I'm remembering right, this probably isn't the best solution. It seems like we have had subtle issues with styling, pdf generation, etc. in the past when files contain more than one top-level heading - the tooling doesn't seem to be designed to handle this case. (also the `uerrno` module would not be in alphabetical order, which looks a bit sloppy).

**Comment by laurensvalk** [comment]
Fixed by commit referenced above.
