### ISSUE TITLE
Too many quotes in auto docstring

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#81]
`"\n"` is shown as `"'\\n'"`.

This seems to happen only with overloaded functions.

![image](https://user-images.githubusercontent.com/12326241/128325888-cfb18113-dca5-4087-8a4c-a39e3f483a7a.png)

**Comment by dlech** [comment]
Sounds like we should raise an issue upstream.

And it is not just the backslash. It seems like there are also too many quotes.

**Comment by laurensvalk** [comment]
This got slightly better in Sphinx 4.1

![image](https://user-images.githubusercontent.com/12326241/128484984-82750dc3-56c7-4c08-8c27-d8c646b71678.png)

**Comment by laurensvalk** [comment]
Conversely, sometimes there are not enough quotes:

![image](https://user-images.githubusercontent.com/12326241/128512098-48be1779-be04-415d-ac43-8ec40b3198f7.png)

**Comment by laurensvalk** [comment]
> Conversely, sometimes there are not enough quotes:

This happens also for (class) methods defined directly in the .rst file.

**Comment by laurensvalk** [comment]
Not sure if it's any help, but there is this alternate [autoapi](https://github.com/readthedocs/sphinx-autoapi) extension we could try instead of autodoc.

We'd probably have to try it on a clean project first because just swapping it in doesn't work.

**Comment by laurensvalk** [comment]
I went back to see when this started happening, but we didn't have many occurences of default string arguments. The closest was `EV3Brick.speaker.set_volume`, which as `"all"` as one of its kwargs. But this is still working.

So this looks to be mostly (only) broken when using overloads. For example, compare ths hack to the screenshot in the first post:

![image](https://user-images.githubusercontent.com/12326241/132189312-43ce1c0e-6197-4b22-b1a3-8869e578b7ef.png)

**Comment by laurensvalk** [comment]
This specific problem:

![image](https://user-images.githubusercontent.com/12326241/132192325-d86f5252-22e4-43b1-afd4-31ec07051d15.png)

seems to be

https://github.com/sphinx-doc/sphinx/issues/8693

which is supposed to be fixed, but perhaps not in the overloaded case.

**Comment by laurensvalk** [comment]
A look through Sphinx' source code does seem to indicate that each overloaded signature is parsed differently (by `stringify_signature`) than a single signature (by `format_signature`).

**Comment by laurensvalk** [comment]
> Conversely, sometimes there are not enough quotes:

This particular one is solved in Sphinx 4.4.

Problem of too many quotes still exists. I am creating a minimally reproducable example so we can submit an upstream bug report.

**Comment by laurensvalk** [comment]
This has been reported upstream and upstream has already [fixed it](https://github.com/sphinx-doc/sphinx/pull/10315)!
