### ISSUE TITLE
Class method docstring missing

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#86]
![image](https://user-images.githubusercontent.com/12326241/128512691-8aa9ed9a-f44a-4127-9ab1-70dacd4aff76.png)

**Comment by laurensvalk** [comment]
We can probably do this one manually.

**Comment by dlech** [comment]
What is the problem? The `classmethod` label is missing?

**Comment by laurensvalk** [comment]
The whole thing is missing - it only shows the name as highlighted in the screenshot above.

**Comment by dlech** [comment]
doh, I didn't even see that

**Comment by laurensvalk** [comment]
The class method issue is fixed but even the manual version still lacks quotes as per #81

**Comment by laurensvalk** [comment]
This looks to have been fixed in Sphinx 4.4, so let's re-open this issue to remove this workaround:

> We can probably do this one manually.

So, drop the copy and let autodoc do it. I can get this to work in a minimal copy, but not yet in pybricks-api.

But at least it should be fixable now.
