### ISSUE TITLE
Build IDE docs with PyPI release

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#88]
It would be nice to build the IDE docs along with the PyPI release and upload them to the release assets. Then when we build the IDE docs JavaScript package, we can just download the html docs from the release instead of having to build them from source. This is similar to how we do the JavaScript package for firmware releases. Doing it this way will make sure that PyPI, Read the Docs and Pybricks Code stay in sync by all using the same release.

**Comment by laurensvalk** [comment]
Is this something for V3.2?

**Comment by laurensvalk** [comment]
Up to you if you think it's worth doing then :)
