### ISSUE TITLE
Add docs for ujson module

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#93]
This was enabled in https://github.com/pybricks/pybricks-micropython/commit/cf833839117deba3746e998853556c4239367c03 so we need to include it in the docs.

**Comment by laurensvalk** [comment]
This was added specifically to parse files for updating the firmware on SPIKE. Since we don't rely on this anymore and since we don't support a file system where you could store json files, how about we disable this module?

**Comment by laurensvalk** [comment]
This is tracked in #63
