### ISSUE TITLE
Docstrings, revisited

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#99]
One of our goals with Pybricks is to have useful documentation. We're still on track, but we basically got a bit stuck on various [technical issues](https://github.com/pybricks/pybricks-api/issues) in an attempt to make things correct and sometimes a bit overly consistent.

I think we can resolve most of this by refining what we are really trying to achieve here: *useful documentation*.

Sometimes, being concise is more helpful than being 100% technically accurate and consistent. Here are a few examples.

**Make type information useful with less bloat**

Having argument type information in the signature can make them very long and hard to read. We can display the type with the argument description instead.

Compare:

![image](https://user-images.githubusercontent.com/12326241/160411731-6f82a2a0-349b-48b3-b4ff-783746e42ee8.png)

to

![image](https://user-images.githubusercontent.com/12326241/160414595-a09b27d0-fc57-4f6f-aab1-0aad3926b914.png)

**Avoid technical terms like `Union` or `Literal` when not needed**

Notice above that:
- `Union[bytes, bytearray]` was changed to (*bytes or bytearray*) in the argument description.
- `Literal["little", "big"]` was changed to simply (`str`), since the description repeats the options anyway. If we want to be more correct, we could also just make it say: (`"little"` or `"big"`).

**Make type information concise**

For *return* types, however, things are easier to follow if we *do* include them in the signature.

Compare:

![image](https://user-images.githubusercontent.com/12326241/160410267-25dfed47-aa96-4479-acb4-71e99fff1224.png)

to:

![image](https://user-images.githubusercontent.com/12326241/160410052-6f6b7618-7d36-4394-a3e6-49f5e3f59ae8.png)

This is especially true for overloaded signatures (not shown here), when each overload has its own return type.

This might seem inconsistent, but it's easy to apply everywhere. Since we can convey the same or more information in a less bloated way, I think it is worth it.

**Be clearer about returning values if no arguments given**

For kwarg arguments like `then=Stop.HOLD`, it is clear that these values are optional. For our return-settings-if-nothing-given, we could be a bit more correct while keeping it concise:

Compare:

![image](https://user-images.githubusercontent.com/12326241/160416054-9389b9d3-abd0-40a0-b768-f56962afe379.png)

to:

![image](https://user-images.githubusercontent.com/12326241/160415945-d3f3099f-ad26-4999-b6ca-7defe81a78ba.png)

**Overly complicated signatures**

This should mostly be deferred to the *.pyi* files.

![image](https://user-images.githubusercontent.com/12326241/160409226-719f5891-6f9a-43bd-8e29-4909a76806c2.png)

**Comment by laurensvalk** [comment]
All in all, I think we can make an effort to doing this, and along the way, try to formalize the rules so we know what to do when we add something new in the future.

We can achieve all of the above without any Python hacks by just including the desired signature in the docstring. This might sound like more work, but it's actually a lot less typing compared to having all the overloads in place.

Since we have separate `.pyi` files anyway, we can use those for the formally correct API, including the details omitted above.

**Comment by dlech** [comment]
> _useful documentation_.

As I have [mentioned before](https://github.com/pybricks/support/issues/612#issuecomment-1017725641), including version information of when an API was added or changed is, without a doubt, the most useful information for me. Without this information, it puts the burden of supporting such changes on those with intimate knowledge of the source code and in my case usually requires digging into the source and git history because I don't remember every thing we did or when we did it.

**Comment by dlech** [comment]
Also, if we are going over all of the `.pyi` files, we can clean up the use of `@overload`. Since we originally created the docs, I' have learned that the actual definition should not have the `@overload` decorator.

**Comment by dlech** [comment]
Another thing to audit in the `.pyi` files is the use of the `/` and `*` separators for positional-only and keyword-only arguments.

**Comment by dlech** [comment]
FYI, I make the comments above as separate comments in case we want to split them out into separate issues. The other changes proposed sound good to me.

**Comment by laurensvalk** [comment]
> From a technical perspective, instead of having separate `.pyi` files, does it work the same to include all of the type hints and overloads in the `.py` files but then override the signatures in the docstring?

Yes, that would be nice. I have tried several other approaches where combining them didn't pan out, but now that we might be back at overriding the docstrings as sketched here, maybe this could work.

[This](https://github.com/pybricks/pybricks-api/issues/87#issuecomment-906133601) could be getting in our way, but that's fairly minor. We could probably even patch it as needed --- suppressing unwanted typing should be easier than magically adding new stuff.

**Comment by laurensvalk** [comment]
> From a technical perspective, instead of having separate .pyi files, does it work the same to include all of the type hints and overloads in the .py files but then override the signatures in the docstring?

With the recent Sphinx patches based on our upstream issue reports, I think this may be achievable now. :smiley:

So we can probably just get this started while we wait for Sphinx 5.0.0 to come out. If we want to release our docs earlier, we might be able to use a pre-release.
